# Generated by Django 6.0.5 on 2026-08-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_promotion_remove_order_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
